### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Scamnex** [Fludixx/Bedwars#8] opened 2019-03-05 14:20 UTC
[15:10:23] [Server thread/CRITICAL]: ErrorException: "file_put_contents(/home/bedwars/stats.json): failed to open stream: No such file or directory" (EXCEPTION) in "src/pocketmine/utils/Config" at line 241

Can u fix this please

**Comment by majovec** [comment] 2019-03-05 17:43
@Scamnex create new folder on home

**Comment by Wertzui123** [comment] 2019-03-15 17:09
Ich hab das gleiche Problem, aber wo ist home bei Minehub? @Scamnex

**Comment by Fludixx** [comment] 2019-06-22 20:57
Duplicate of #3

**Closed as completed by Fludixx** 2019-06-22 20:57 UTC
