### ISSUE TITLE
Error can you help me?

### ISSUE THREAD

**Issue by DavidPernutz** [Fludixx/Bedwars#7] opened 2019-03-03 11:19 UTC
2019-03-03 [12:14:10] [Server thread/INFO]: Enabling Bedwars v1.4
2019-03-03 [12:14:10] [Server thread/CRITICAL]: ErrorException: "file_put_contents(/home/bedwars/stats.json): failed to open stream: No such file or directory" (EXCEPTION) in "src/pocketmine/utils/Config" at line 241
2019-03-03 [12:14:10] [Server thread/DEBUG]: #0 (): pocketmine\utils\Utils::errorExceptionHandler(integer 2, string file_put_contents(/home/bedwars/stats.json): failed to open stream: No such file or directory, string phar:///home/minecraft/pocketmine.phar/src/pocketmine/utils/Config.php, integer 241, array Array())
2019-03-03 [12:14:10] [Server thread/DEBUG]: #1 src/pocketmine/utils/Config(241): file_put_contents(string /home/bedwars/stats.json, string [])
2019-03-03 [12:14:10] [Server thread/DEBUG]: #2 src/pocketmine/utils/Config(168): pocketmine\utils\Config->save()
2019-03-03 [12:14:10] [Server thread/DEBUG]: #3 src/pocketmine/utils/Config(113): pocketmine\utils\Config->load(string /home/bedwars/stats.json, integer -1, array Array())
2019-03-03 [12:14:10] [Server thread/DEBUG]: #4 plugins/Bedwars-master.phar/src/Fludixx/Bedwars/ranking/JsonStats(30): pocketmine\utils\Config->__construct(string /home/bedwars/stats.json)
2019-03-03 [12:14:10] [Server thread/DEBUG]: #5 plugins/Bedwars-master.phar/src/Fludixx/Bedwars/Bedwars(94): Fludixx\Bedwars\ranking\JsonStats->__construct()
2019-03-03 [12:14:10] [Server thread/DEBUG]: #6 src/pocketmine/plugin/PluginBase(123): Fludixx\Bedwars\Bedwars->onEnable()
2019-03-03 [12:14:10] [Server thread/DEBUG]: #7 src/pocketmine/plugin/PluginManager(587): pocketmine\plugin\PluginBase->setEnabled(boolean 1)
2019-03-03 [12:14:10] [Server thread/DEBUG]: #8 src/pocketmine/Server(2002): pocketmine\plugin\PluginManager->enablePlugin(Fludixx\Bedwars\Bedwars object)
2019-03-03 [12:14:10] [Server thread/DEBUG]: #9 src/pocketmine/Server(1988): pocketmine\Server->enablePlugin(Fludixx\Bedwars\Bedwars object)
2019-03-03 [12:14:10] [Server thread/DEBUG]: #10 src/pocketmine/Server(1782): pocketmine\Server->enablePlugins(integer 1)
2019-03-03 [12:14:10] [Server thread/DEBUG]: #11 src/pocketmine/PocketMine(250): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /home/minecraft/, string /home/minecraft/plugins/)
2019-03-03 [12:14:10] [Server thread/DEBUG]: #12 (1): require(string phar:///home/minecraft/pocketmine.phar/src/pocketmine/PocketMine.php)
2019-03-03 [12:14:10] [Server thread/INFO]: Disabling Bedwars v1.4
2019-03-03 [12:14:10] [Server thread/INFO]: [Bedwars] All stats were saved!

**Comment by Fludixx** [comment] 2019-06-22 20:57
Duplicate of #3

**Closed as completed** 2019-06-22 20:58 UTC
